-- Cria tabela de histórico de lembretes/cobranças enviados
CREATE TABLE IF NOT EXISTS public.charge_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_id text NOT NULL,
    material_id text NOT NULL,
    person_email text NOT NULL,
    person_name text NOT NULL,
    sent_at timestamptz NOT NULL DEFAULT now(),
    triggered_by_name text NOT NULL,
    triggered_by_email text,
    campus_id text
);

CREATE INDEX IF NOT EXISTS idx_charge_history_loan_id ON public.charge_history (loan_id);
CREATE INDEX IF NOT EXISTS idx_charge_history_sent_at ON public.charge_history (sent_at);

-- Habilita RLS
ALTER TABLE public.charge_history ENABLE ROW LEVEL SECURITY;

-- Permite tudo (modo compatibilidade)
DROP POLICY IF EXISTS "Acesso Total Charge History" ON public.charge_history;
CREATE POLICY "Acesso Total Charge History" ON public.charge_history
    FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
